import { promises as fs } from "node:fs"
import path from "node:path"
import process from "node:process"
import { parseDocument } from "yaml"

const fallbackVault = "/Users/anthol/1. Projects/4. Kunskapsbas/4.1 second-brain"
const vault = path.resolve(process.env.OBSIDIAN_VAULT || fallbackVault)
const output = path.resolve("content/garden/notes")
const marker = path.join(output, ".generated-by-export-garden")
const write = process.argv.includes("--write")

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(full)))
    else files.push(full)
  }
  return files
}

function frontmatter(source) {
  if (!source.startsWith("---")) return {}
  const end = source.indexOf("\n---", 3)
  if (end === -1) return {}
  return parseDocument(source.slice(3, end)).toJS() || {}
}

function referencedAssets(source) {
  const refs = new Set()
  for (const match of source.matchAll(/!\[\[([^\]|#]+)(?:[|#][^\]]*)?\]\]/g)) refs.add(match[1])
  for (const match of source.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g)) {
    const target = match[1].split(/\s+["']/)[0]
    if (!/^(?:https?:|data:|\/)/.test(target)) refs.add(decodeURIComponent(target))
  }
  return refs
}

const all = await walk(vault)
const markdown = all.filter((file) => file.endsWith(".md"))
const published = []

for (const file of markdown) {
  const source = await fs.readFile(file, "utf8")
  if (frontmatter(source).publish === true) published.push({ file, source })
}

const assets = new Set()
for (const note of published) {
  for (const ref of referencedAssets(note.source)) {
    const besideNote = path.resolve(path.dirname(note.file), ref)
    const byVaultPath = path.resolve(vault, ref)
    const exact = all.find((file) => file === besideNote || file === byVaultPath)
    const byName = all.find((file) => path.basename(file) === path.basename(ref))
    const asset = exact || byName
    if (asset && !asset.endsWith(".md")) assets.add(asset)
  }
}

console.log(
  `Garden export: ${published.length} published note(s), ${assets.size} referenced asset(s).`,
)
for (const note of published) console.log(`  note  ${path.relative(vault, note.file)}`)
for (const asset of assets) console.log(`  asset ${path.relative(vault, asset)}`)

if (!write) {
  console.log("Dry run only. Add --write to update content/garden/notes.")
  process.exit(0)
}

try {
  await fs.access(output)
  await fs.access(marker)
  await fs.rm(output, { recursive: true })
} catch (error) {
  if (error.code !== "ENOENT") {
    throw new Error("Refusing to replace an unmarked garden export directory.")
  }
}

await fs.mkdir(output, { recursive: true })
await fs.writeFile(marker, "Generated by scripts/export-garden.mjs\n")

for (const note of published) {
  const relative = path.relative(vault, note.file)
  const destination = path.join(output, relative)
  await fs.mkdir(path.dirname(destination), { recursive: true })
  await fs.copyFile(note.file, destination)
}

for (const asset of assets) {
  const relative = path.relative(vault, asset)
  const destination = path.join(output, relative)
  await fs.mkdir(path.dirname(destination), { recursive: true })
  await fs.copyFile(asset, destination)
}

console.log("Garden export updated.")
